### ISSUE TITLE
NestJs Template for mock-backends

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/ngx-hawk#14]
## Background

Would be nice to be able to quickly set up a backend generating test data lazily.

### Why lazy data generation

- Creating more than 10.000 test data entries is quiet time-consuming
- Data should be generated and cached as needed.

## Benefit

- Allows working offline

## ToDos

- [ ] Find easy way to generate test data
- [ ] Provide Tooling to spin up Backend Endpoints (schematics)
- [ ] Figure out an easy way to query relational data
- [ ] Allow configuring latency (maybe changeable at runtime without restarting the server...)
- [ ] Randomly return errors to get a feeling of the real world ... (maybe have a look of chaos computing patterns/tools)

## Possible Areas

- RESTful API
- GraphQL API
- Micro Service
